/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-03-15 08:27:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import project.ConnectionProvider;
import java.sql.*;

public final class myCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1615714671063L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1615795968860L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("project.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/home-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tfont-family: 'Roboto Mono', monospace;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tpadding: 20px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 12px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a.logo {\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a.active {\r\n");
      out.write("\tbackground-color: dodgerblue;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 500px) {\r\n");
      out.write("\t.header a {\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header-right {\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t");

	String email = session.getAttribute("email").toString();
	
      out.write("\r\n");
      out.write("\t<a href=\"home.jsp\" class=\"logo\">Supermarket Management System</a>\r\n");
      out.write("\t<div class=\"header-right\">\r\n");
      out.write("\t\t<a style=\"text-decoration: none;\"> ");
 out.println(email); 
      out.write("&nbsp;<i\r\n");
      out.write("\t\t\tclass='fas fa-user-alt'></i>\r\n");
      out.write("\t\t</a> \r\n");
      out.write("\t\t<a href=\"home.jsp\">Home&nbsp;<i class=\"fa fa-institution\"></i></a> \r\n");
      out.write("\t\t<a href=\"myCart.jsp\">My Cart&nbsp;<i class='fas fa-cart-arrow-down'></i></a>\r\n");
      out.write("\t\t<a href=\"myOrders.jsp\">My Orders&nbsp;<i class='fab fa-elementor'></i></a>\r\n");
      out.write("\t\t<a href=\"logout.jsp\">Logout&nbsp;<i class='fas fa-share-square'></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>");
      out.write('\r');
      out.write('\n');
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<p>All Right Reserved @Supermarket Management System</p>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>My Cart</title>\r\n");
      out.write("<style>\r\n");
      out.write("h3 {\r\n");
      out.write("\tcolor: yellow;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remove {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground-color: #dc3545;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground-color: #28a745;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-right: 40px;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding: .75rem 1.25rem;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\tborder-radius: .25rem;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert-success {\r\n");
      out.write("\tcolor: #155724;\r\n");
      out.write("\tbackground-color: #d4edda;\r\n");
      out.write("\tborder-color: #c3e6cb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert-danger {\r\n");
      out.write("\tcolor: #721c24;\r\n");
      out.write("\tbackground-color: #f8d7da;\r\n");
      out.write("\tborder-color: #f5c6cb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert-warning {\r\n");
      out.write("\tcolor: #856404;\r\n");
      out.write("\tbackground-color: #fff3cd;\r\n");
      out.write("\tborder-color: #ffeeba;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".proceed {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground-color: #28a745;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-right: 40px;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"color: white; text-align: center; font-size: 30px;\">\r\n");
      out.write("\t\tMy Cart <i class='fas fa-cart-arrow-down'></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	String msg = request.getParameter("msg");
	if ("notPossible".equals(msg)) {
	
      out.write("\r\n");
      out.write("\t<h3 class=\"alert alert-warning\">There is only one Quantity! So\r\n");
      out.write("\t\tclick on remove!</h3>\r\n");
      out.write("\t");

	}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	if ("inc".equals(msg)) {
	
      out.write("\r\n");
      out.write("\t<h3 class=\"alert alert-success\">Quantity Increased Successfully!</h3>\r\n");
      out.write("\t");

	}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	if ("dec".equals(msg)) {
	
      out.write("\r\n");
      out.write("\t<h3 class=\"alert alert-danger\">Quantity Decreased Successfully!</h3>\r\n");
      out.write("\t");

	}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	if ("remove".equals(msg)) {
	
      out.write("\r\n");
      out.write("\t<h3 class=\"alert alert-danger\">Product Successfully Removed!</h3>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t");

			int total = 0;
			int sno = 0;
			try {
				Connection con = ConnectionProvider.getCon();
				Statement st = con.createStatement();
				ResultSet rs1 = st.executeQuery("select sum(total) from cart where email='" + email + "' and address is NULL");
				while (rs1.next()) {
					total = rs1.getInt(1);
				}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"col\" style=\"background-color: #28a745;\">Total:&nbsp;<i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-inr\"></i>&nbsp;");
 out.println(total); 
      out.write("\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t");

				// if(total>0){
				
      out.write("\r\n");
      out.write("\t\t\t\t");

				// }
				
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">S.No</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">Product Name</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">Category</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\"><i class=\"fa fa-inr\"></i> price</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">Quantity</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">Sub Total</th>\r\n");
      out.write("\t\t\t\t<th scope=\"col\">Remove <i class='fas fa-trash-alt'></i></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t");

			ResultSet rs = st.executeQuery("select * from product inner join cart on product.id=cart.product_id and cart.email='"
					+ email + "' and cart.address is NULL");
			while (rs.next()) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

				sno = sno + 1;
				
      out.write("\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");

					out.println(sno);
					
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><i class=\"fa fa-inr\"></i>&nbsp;");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a style=\"color: black;\"\r\n");
      out.write("\t\t\t\t\thref=\"incDecQuantityAction.jsp?id=");
      out.print(rs.getString(1));
      out.write("&quantity=inc\">\r\n");
      out.write("\t\t\t\t\t\t<i class='fas fa-plus-circle'></i>\r\n");
      out.write("\t\t\t\t</a> &nbsp;");
      out.print(rs.getString(8));
      out.write("&nbsp; <a style=\"color: black;\"\r\n");
      out.write("\t\t\t\t\thref=\"incDecQuantityAction.jsp?id=");
      out.print(rs.getString(1));
      out.write("&quantity=dec\">\r\n");
      out.write("\t\t\t\t\t\t<i class='fas fa-minus-circle'></i>\r\n");
      out.write("\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t<td><i class=\"fa fa-inr\"></i>&nbsp;");
      out.print(rs.getString(10));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a class=\"remove\"\r\n");
      out.write("\t\t\t\t\thref=\"removeFromCart.jsp?id=");
      out.print(rs.getString(1));
      out.write("\">Remove <i\r\n");
      out.write("\t\t\t\t\t\tclass='fas fa-trash-alt'></i>\r\n");
      out.write("\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

			}

			} catch (Exception e) {
			}
			
      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- <button class=\"order\">Proceed to order</button> -->\r\n");
      out.write("\t<a class=\"proceed\" href=\"proceedOrder.jsp?\">Proceed to order</a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
